[package]
name = "sysadmin"
version = "0.1.0"
authors = ["Matt McKay <mckaymatt@gmail.com>"]

[dependencies]
protobuf = "1.4.2"
bufstream = "0.1.3"
bytes = "0.4.*"
byteorder = "1.1.0"


[build-dependencies]
protoc-rust = "1.4"
